cc_test(
    name = 'Atomic_unittest',
    srcs = [
        'Atomic_unittest.cc',
    ],
    deps = [
        '//essence/muduo/base:base',
    ]
)

cc_test(
    name = 'BlockingQueue_bench',
    srcs = [
        'BlockingQueue_bench.cc',
    ],
    deps = [
        '//essence/muduo/base:base',
    ]
)

cc_test(
    name = 'Date_unittest',
    srcs = [
        'Date_unittest.cc',
    ],
    deps = [
        '//essence/muduo/base:base',
    ]
)

cc_test(
    name = 'LogStream_bench',
    srcs = [
        'LogStream_bench.cc',
    ],
    deps = [
        '//essence/muduo/base:base',
    ]
)

cc_test(
    name = 'Thread_bench',
    srcs = [
        'Thread_bench.cc',
    ],
    deps = [
        '//essence/muduo/base:base',
    ]
)

cc_test(
    name = 'Timestamp_unittest',
    srcs = [
        'Timestamp_unittest.cc',
    ],
    deps = [
        '//essence/muduo/base:base',
    ]
)

cc_test(
    name = 'TimeZone_unittest',
    srcs = [
        'TimeZone_unittest.cc',
    ],
    deps = [
        '//essence/muduo/base:base',
    ]
)

cc_test(
    name = 'AsyncLogging_test',
    srcs = ['AsyncLogging_test.cc'],
    deps = [
        '//essence/muduo/base:base',
    ]
)


cc_test(
    name = 'BlockingQueue_test',
    srcs = ['BlockingQueue_test.cc'],
    deps = [
        '//essence/muduo/base:base',
    ]
)


cc_test(
    name = 'BoundedBlockingQueue_test',
    srcs = ['BoundedBlockingQueue_test.cc'],
    deps = [
        '//essence/muduo/base:base',
    ]
)


cc_test(
    name = 'Exception_test',
    srcs = ['Exception_test.cc'],
    deps = [
        '//essence/muduo/base:base',
    ]
)


cc_test(
    name = 'FileUtil_test',
    srcs = ['FileUtil_test.cc'],
    deps = [
        '//essence/muduo/base:base',
    ]
)


cc_test(
    name = 'Fork_test',
    srcs = ['Fork_test.cc'],
    deps = [
        '//essence/muduo/base:base',
    ]
)


cc_test(
    name = 'LogFile_test',
    srcs = ['LogFile_test.cc'],
    deps = [
        '//essence/muduo/base:base',
    ]
)


cc_test(
    name = 'Logging_test',
    srcs = ['Logging_test.cc'],
    deps = [
        '//essence/muduo/base:base',
    ]
)


cc_test(
    name = 'LogStream_test',
    warning = 'no',
    srcs = ['LogStream_test.cc'],
    deps = [
        '//essence/muduo/base:base',
    ]
)


cc_test(
    name = 'Mutex_test',
    srcs = ['Mutex_test.cc'],
    deps = [
        '//essence/muduo/base:base',
    ]
)


cc_test(
    name = 'ProcessInfo_test',
    srcs = ['ProcessInfo_test.cc'],
    deps = [
        '//essence/muduo/base:base',
    ]
)


cc_test(
    name = 'Singleton_test',
    srcs = ['Singleton_test.cc'],
    deps = [
        '//essence/muduo/base:base',
    ]
)


cc_test(
    name = 'SingletonThreadLocal_test',
    srcs = ['SingletonThreadLocal_test.cc'],
    deps = [
        '//essence/muduo/base:base',
    ]
)


cc_test(
    name = 'ThreadLocalSingleton_test',
    srcs = ['ThreadLocalSingleton_test.cc'],
    deps = [
        '//essence/muduo/base:base',
    ]
)


cc_test(
    name = 'ThreadLocal_test',
    srcs = ['ThreadLocal_test.cc'],
    deps = [
        '//essence/muduo/base:base',
    ]
)


cc_test(
    name = 'ThreadPool_test',
    srcs = ['ThreadPool_test.cc'],
    deps = [
        '//essence/muduo/base:base',
    ]
)


cc_test(
    name = 'Thread_test',
    srcs = ['Thread_test.cc'],
    deps = [
        '//essence/muduo/base:base',
    ]
)
