cc_library(
    name = 'inspect',
    srcs = [
        'Inspector.cc',
        'PerformanceInspector.cc',
        'ProcessInspector.cc',
    ],
    deps = [
        '//essence/muduo/net/http:http',
    ]
)
