cc_binary(
  name = 'download',
  srcs = [
    'download.cc',
  ],
  deps = '//essence/muduo:muduo',
)

cc_binary(
  name = 'download2',
  srcs = [
    'download2.cc',
  ],
  deps = '//essence/muduo:muduo',
)

cc_binary(
  name = 'download3',
  srcs = [
    'download3.cc',
  ],
  deps = '//essence/muduo:muduo',
)
