cc_binary(
  name = 'chat_client',
  srcs = [
    'client.cc',
  ],
  deps = '//essence/muduo:muduo',
)

cc_binary(
  name = 'chat_loadtest',
  srcs = [
    'loadtest.cc',
  ],
  deps = '//essence/muduo:muduo',
)

cc_binary(
  name = 'chat_server',
  srcs = [
    'server.cc',
  ],
  deps = '//essence/muduo:muduo',
)

cc_binary(
  name = 'chat_server_threaded',
  srcs = [
    'server_threaded.cc',
  ],
  deps = '//essence/muduo:muduo',
)

cc_binary(
  name = 'chat_server_threaded_efficient',
  srcs = [
    'server_threaded_efficient.cc',
  ],
  deps = '//essence/muduo:muduo',
)

cc_binary(
  name = 'chat_server_threaded_highperformance',
  srcs = [
    'server_threaded_highperformance.cc',
  ],
  deps = '//essence/muduo:muduo',
)
