cc_binary(
  name = 'finger01',
  srcs = [
    'finger01.cc',
  ],
  deps = '//muduo:muduo'
)

cc_binary(
  name = 'finger02',
  srcs = [
    'finger02.cc',
  ],
  deps = '//muduo:muduo'
)

cc_binary(
  name = 'finger03',
  srcs = [
    'finger03.cc',
  ],
  deps = '//muduo:muduo'
)

cc_binary(
  name = 'finger04',
  srcs = [
    'finger04.cc',
  ],
  deps = '//muduo:muduo'
)

cc_binary(
  name = 'finger05',
  srcs = [
    'finger05.cc',
  ],
  deps = '//muduo:muduo'
)

cc_binary(
  name = 'finger06',
  srcs = [
    'finger06.cc',
  ],
  deps = '//muduo:muduo'
)

cc_binary(
  name = 'finger07',
  srcs = [
    'finger07.cc',
  ],
  deps = '//muduo:muduo'
)

