cc_test(
    name = 'Buffer_unittest',
    warning = 'no',
    srcs = [
        'Buffer_unittest.cc',
    ],
    deps = [
        '//essence/muduo/net:net',
    ]
)

cc_binary(
    name = 'EchoClient_unittest',
    srcs = [
        'EchoClient_unittest.cc',
    ],
    deps = [
        '//essence/muduo/net:net',
    ]
)

cc_binary(
    name = 'EchoServer_unittest',
    srcs = [
        'EchoServer_unittest.cc',
    ],
    deps = [
        '//essence/muduo/net:net',
    ]
)

cc_test(
    name = 'EventLoopThreadPool_unittest',
    srcs = [
        'EventLoopThreadPool_unittest.cc',
    ],
    deps = [
        '//essence/muduo/net:net',
    ]
)

cc_test(
    name = 'EventLoopThread_unittest',
    srcs = [
        'EventLoopThread_unittest.cc',
    ],
    deps = [
        '//essence/muduo/net:net',
    ]
)

cc_test(
    name = 'EventLoop_unittest',
    srcs = [
        'EventLoop_unittest.cc',
    ],
    deps = [
        '//essence/muduo/net:net',
    ]
)

cc_test(
    name = 'InetAddress_unittest',
    warning = 'no',
    srcs = [
        'InetAddress_unittest.cc',
    ],
    deps = [
        '//essence/muduo/net:net',
    ]
)

cc_test(
    name = 'TcpClient_reg1',
    srcs = [
        'TcpClient_reg1.cc',
    ],
    deps = [
        '//essence/muduo/net:net',
    ]
)

cc_test(
    name = 'TimerQueue_unittest',
    srcs = [
        'TimerQueue_unittest.cc',
    ],
    deps = [
        '//essence/muduo/net:net',
    ]
)
