cc_binary(
  name = 'echo',
  srcs = [
    'echo.cc',
    'main.cc',
  ],
  deps = '//essence/muduo:muduo',
)

cc_binary(
  name = 'echo_sorted_list',
  srcs = [
    'sortedlist.cc',
  ],
  deps = '//essence/muduo:muduo',
)
