cc_test(
    name = 'HttpRequest_unittest',
    warning = 'no',
    srcs = [
        'HttpRequest_unittest.cc',
    ],
    deps = [
        '//essence/muduo/net/http:http',
    ]    
)

cc_binary(
    name = 'HttpServer_test',
    srcs = ['HttpServer_test.cc'],
    deps = [
        '//essence/muduo/net/http:http',
    ]    
)
