cc_library(
  name = 'base',
  warning = 'no',
  extra_cppflags = '-std=c++0x',
  srcs = [
    'AsyncLogging.cc',
    'Condition.cc',
    'CountDownLatch.cc',
    'Date.cc',
    'Exception.cc',
    'FileUtil.cc',
    'LogFile.cc',
    'Logging.cc',
    'LogStream.cc',
    'ProcessInfo.cc',
    'Thread.cc',
    'ThreadPool.cc',
    'Timestamp.cc',
    'TimeZone.cc',
  ],
  deps = [
    '#pthread',
    '#rt',
  ]
)
